# Da Api Client
da_api_client:
    api:
        participation:
            endpoint_root: %api.participation.endpoint_root%
            security_token: %api.security_token%
#            cache_enabled: true
        operation:
            endpoint_root:  %api.operation.endpoint_root%
            security_token: %api.security_token%
#           cache_enabled:  true
#        pot:
#                endpoint_root:  %api.pot.endpoint_root%
#                security_token: %api.security_token%
#                cache_enabled:  true
#        code:
#                endpoint_root:  %api.code.endpoint_root%
#                security_token: %api.security_token%
#                cache_enabled:  true

# Knp snappy PDF Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options:
            margin_bottom: 0
            margin_left: 0
            margin_right: 0
            margin_top: 0

# FOSRest Configuration
fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: force
    service:
        serializer: jms_serializer.serializer
    serializer:
        version: ~
        groups: []
        serialize_null: false

# JMS Serializer
jms_serializer:
    metadata:
        auto_detection: true

# TMS Rest
tms_rest:
#    default:
#        pagination:
#            limit:
#                default: 500
#                maximum: 1500
#            sort:
#                field: id
#                order: asc
#            offset:
#                default: 0
#            page:
#                default: 1
    routes:
        api_templates_get_templates:
            pagination:
                limit:
                    default: 20
                    maximum: 1000
#                sort:
#                    field: id
#                    order: asc
#                offset:
#                    default: 0
#                page:
#                    default: 1

# IDCI Metadata
idci_simple_metadata:
    namespaces: [tags]