twig:
    form:
        resources:
            - 'TmsDocumentGeneratorBundle:Form:fields.html.twig'

# Metadata
idci_simple_metadata:
    namespaces: [tags]

tms_document_generator:
    formats:
        pdf: tms_document_generator.generator.dompdf
        html: tms_document_generator.generator.html_default

# Model IO
tms_model_io:
    models:
        template:
            object_manager: doctrine
            class: Tms\Bundle\DocumentGeneratorBundle\Entity\Template
            modes:
                full:
                    - name
                    - description
                    - tags: {mode: simple}
                    - html
                    - css
                    - mergeTags: {mode: simple}
                    - images: {mode: simple}
        merge_tag:
            object_manager: doctrine
            class: Tms\Bundle\DocumentGeneratorBundle\Entity\MergeTag
            aliases: ["mergeTags"]
            modes:
                simple:
                    - name
                    - required
                    - identifier
        images:
            object_manager: doctrine
            class: Tms\Bundle\MediaClientBundle\Entity\Media
            modes:
                simple:
                    - url
                    - mimeType
                    - providerName
                    - providerReference
                    - providerData
                    - extension
        tags:
            object_manager: doctrine
            class: IDCI\Bundle\SimpleMetadataBundle\Entity\Metadata
            modes:
                simple:
                    - namespace
                    - key
                    - value
                    - hash
                    - objectClassName
                    - objectId
