twig:
    form:
        resources:
            - 'TmsDocumentGeneratorBundle:Form:fields.html.twig'

# Metadata
idci_simple_metadata:
    namespaces: [tags]

tms_document_generator:
    formats:
        pdf: tms_document_generator.generator.dompdf
        html: tms_document_generator.generator.html_default
