services:
    tms_document_generator.manager.template:
        class: Tms\Bundle\DocumentGeneratorBundle\Manager\TemplateManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]

    tms_document_generator.manager.merge_tag:
        class: Tms\Bundle\DocumentGeneratorBundle\Manager\MergeTagManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]