services:

    #Generator
    tms_document_generator:
        class: Tms\Bundle\DocumentGeneratorBundle\Generator\Generator
        arguments:
            - @tms_document_generator.manager.template
            - @tms_document_generator.fetcher.registry
            - @tms_document_generator.converter.registry

    #Registry
    tms_document_generator.fetcher.registry:
        class: Tms\Bundle\DocumentGeneratorBundle\DataFetcher\DataFetcherRegistry

    tms_document_generator.converter.registry:
        class: Tms\Bundle\DocumentGeneratorBundle\HtmlConverter\HtmlConverterRegistry

    #Fetcher
    tms_document_generator.fetcher.default:
        class: Tms\Bundle\DocumentGeneratorBundle\DataFetcher\DefaultDataFetcher
        arguments: [@tms_rest_client.hypermedia.crawler]
        tags:
            - { name: tms_document_generator.fetcher, alias: default }

    tms_document_generator.fetcher.user:
        class: Tms\Bundle\DocumentGeneratorBundle\DataFetcher\UserDataFetcher
        arguments: [@tms_rest_client.hypermedia.crawler]
        tags:
            - { name: tms_document_generator.fetcher, alias: user }

    tms_document_generator.fetcher.participation:
        class: Tms\Bundle\DocumentGeneratorBundle\DataFetcher\ParticipationDataFetcher
        arguments: [@tms_rest_client.hypermedia.crawler]
        tags:
            - { name: tms_document_generator.fetcher, alias: participation }

    #Converter
    tms_document_generator.converter.pdf:
        class: Tms\Bundle\DocumentGeneratorBundle\HtmlConverter\PdfHtmlConverter
        arguments: [@knp_snappy.pdf]
        tags:
            - { name: tms_document_generator.converter, alias: pdf }