services:
    tms_bundle_documentgeneratorbundle.form.type.template:
        class: Tms\Bundle\DocumentGeneratorBundle\Form\Type\TemplateType
        tags:
            - { name: form.type, alias: template }