services:
    tms_document_generator.generator.dompdf:
        class: Tms\Bundle\DocumentGeneratorBundle\Generator\DompdfGenerator

    tms_document_generator.generator.html_default:
        class: Tms\Bundle\DocumentGeneratorBundle\Generator\HtmlDefaultGenerator

    tms_document_generator.security:
        class: Tms\Bundle\DocumentGeneratorBundle\Security\Security
