<?php

namespace Tms\Bundle\DocumentGeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Tms\Bundle\DocumentGeneratorBundle\Entity\Template;

/**
 * MergeTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergeTagRepository extends AbstractEntityRepository
{
    /**
     * Duplicate merge tags of template
     *
     * @param Template $template
     * @param Template $templateDuplicated
     */
    public function duplicate(Template $template, Template $templateDuplicated)
    {
        foreach ($template->getMergeTags() as $mergeTag) {
            $newMergeTag = clone $mergeTag;
            $newMergeTag->setTemplate($templateDuplicated);
            $this->getEntityManager()->persist($newMergeTag);
            $this->getEntityManager()->flush();
        }
    }
}
