<?php

namespace Tms\Bundle\DocumentGeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Tms\Bundle\DocumentGeneratorBundle\Entity\Template;

/**
 * MergeTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergeTagRepository extends AbstractEntityRepository
{

}
