<?php

namespace Tms\Bundle\DocumentGeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use IDCI\Bundle\SimpleMetadataBundle\Entity\Metadata;
use Tms\Bundle\DocumentGeneratorBundle\Entity\Template;
use Tms\Bundle\MediaClientBundle\Entity\Media;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends AbstractEntityRepository
{

}
