Tms\Bundle\DocumentGeneratorBundle\Entity\MergeTag:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        identifier:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        required:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        description:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        fetcherAlias:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        defaultValue:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

