Tms\Bundle\DocumentGeneratorBundle\Entity\Template:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        name:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        createdAt:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]
            serialized_name: createdAt

        description:
            expose: true
            groups: [tms_rest.item]

        mergeTags:
            expose: true
            groups: [tms_rest.item]

        html:
            expose: true
            groups: [tms_rest.item]

        css:
            expose: true
            groups: [tms_rest.item]